const gameinfo = () => {
    currentgameversion = '1.4';

    characters = [
        ['Argenti', 'Argenti'],
        ['Arlan', 'Arlan'],
        ['Asta', 'Asta'],
        ['Bailu', 'Bailu'],
        ['Blade', 'Blade'],
        ['Bronya', 'Bronya'],
        ['Clara', 'Clara'],
        ['DanHeng', 'Dan Heng'],
        ['DanHeng_IL', 'Dan Heng - Imbibitor Lunae'],
        ['DrRatio', 'Dr.Ratio'],
        ['FuXuan', 'Fu Xuan'],
        ['Gepard', 'Gepard'],
        ['Guinaifen', 'Guinaifen'],
        ['Hanya', 'Hanya'],
        ['Herta', 'Herta'],
        ['Himeko', 'Himeko'],
        ['Hook', 'Hook'],
        ['Huohuo', 'Huohuo'],
        ['Jingliu', 'Jingliu'],
        ['JingYuan', 'Jing Yuan'],
        ['Kafka', 'Kafka'],
        ['Luka', 'Luka'],
        ['Luocha', 'Luocha'],
        ['Lynx', 'Lynx'],
        ['March7th', 'March 7th'],
        ['Natasha', 'Natasha'],
        ['Pela', 'Pela'],
        ['Qingque', 'Qingque'],
        ['RuanMei', 'Ruan Mei'],
        ['Sampo', 'Sampo'],
        ['Seele', 'Seele'],
        ['Serval', 'Serval'],
        ['SilverWolf', 'Silver Wolf'],
        ['Sushang', 'Sushang'],
        ['Tingyun', 'Tingyun'],
        ['Topaz', 'Topaz'],
        ['TrailblazerDestruction', 'Trailblazer - Destruction'],
        ['TrailblazerPreservation', 'Trailblazer - Preservation'],
        ['Welt', 'Welt'],
        ['Xueyi', 'Xueyi'],
        ['Yanqing', 'Yanqing'],
        ['Yukong', 'Yukong'],
    ];
}

export default gameinfo;